[package]
name = "SQLdumpRust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oracle = "0.5.3"
r2d2 = "0.8.9"
r2d2-oracle = "0.2.0"
structopt = "0.3"
